/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as AlienIndexImport } from './routes/alien/index'
import { Route as ScientistLoginImport } from './routes/scientist/login'
import { Route as AlienLoginImport } from './routes/alien/login'
import { Route as AlienGameImport } from './routes/alien/game'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AlienIndexRoute = AlienIndexImport.update({
  id: '/alien/',
  path: '/alien/',
  getParentRoute: () => rootRoute,
} as any)

const ScientistLoginRoute = ScientistLoginImport.update({
  id: '/scientist/login',
  path: '/scientist/login',
  getParentRoute: () => rootRoute,
} as any)

const AlienLoginRoute = AlienLoginImport.update({
  id: '/alien/login',
  path: '/alien/login',
  getParentRoute: () => rootRoute,
} as any)

const AlienGameRoute = AlienGameImport.update({
  id: '/alien/game',
  path: '/alien/game',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/alien/game': {
      id: '/alien/game'
      path: '/alien/game'
      fullPath: '/alien/game'
      preLoaderRoute: typeof AlienGameImport
      parentRoute: typeof rootRoute
    }
    '/alien/login': {
      id: '/alien/login'
      path: '/alien/login'
      fullPath: '/alien/login'
      preLoaderRoute: typeof AlienLoginImport
      parentRoute: typeof rootRoute
    }
    '/scientist/login': {
      id: '/scientist/login'
      path: '/scientist/login'
      fullPath: '/scientist/login'
      preLoaderRoute: typeof ScientistLoginImport
      parentRoute: typeof rootRoute
    }
    '/alien/': {
      id: '/alien/'
      path: '/alien'
      fullPath: '/alien'
      preLoaderRoute: typeof AlienIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alien/game': typeof AlienGameRoute
  '/alien/login': typeof AlienLoginRoute
  '/scientist/login': typeof ScientistLoginRoute
  '/alien': typeof AlienIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alien/game': typeof AlienGameRoute
  '/alien/login': typeof AlienLoginRoute
  '/scientist/login': typeof ScientistLoginRoute
  '/alien': typeof AlienIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/alien/game': typeof AlienGameRoute
  '/alien/login': typeof AlienLoginRoute
  '/scientist/login': typeof ScientistLoginRoute
  '/alien/': typeof AlienIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alien/game'
    | '/alien/login'
    | '/scientist/login'
    | '/alien'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alien/game' | '/alien/login' | '/scientist/login' | '/alien'
  id:
    | '__root__'
    | '/'
    | '/alien/game'
    | '/alien/login'
    | '/scientist/login'
    | '/alien/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlienGameRoute: typeof AlienGameRoute
  AlienLoginRoute: typeof AlienLoginRoute
  ScientistLoginRoute: typeof ScientistLoginRoute
  AlienIndexRoute: typeof AlienIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlienGameRoute: AlienGameRoute,
  AlienLoginRoute: AlienLoginRoute,
  ScientistLoginRoute: ScientistLoginRoute,
  AlienIndexRoute: AlienIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/alien/game",
        "/alien/login",
        "/scientist/login",
        "/alien/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/alien/game": {
      "filePath": "alien/game.tsx"
    },
    "/alien/login": {
      "filePath": "alien/login.tsx"
    },
    "/scientist/login": {
      "filePath": "scientist/login.tsx"
    },
    "/alien/": {
      "filePath": "alien/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
