/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './Routes/__root'
import { Route as IndexImport } from './Routes/index'
import { Route as AlienIndexImport } from './Routes/alien/index'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AlienIndexRoute = AlienIndexImport.update({
  id: '/alien/',
  path: '/alien/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/alien/': {
      id: '/alien/'
      path: '/alien'
      fullPath: '/alien'
      preLoaderRoute: typeof AlienIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alien': typeof AlienIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alien': typeof AlienIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/alien/': typeof AlienIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/alien'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/alien'
  id: '__root__' | '/' | '/alien/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlienIndexRoute: typeof AlienIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlienIndexRoute: AlienIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/alien/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/alien/": {
      "filePath": "alien/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
