services:
  db:
    container_name: message_db
    image: postgres:latest
    environment:
      POSTGRES_USER: messageuser
      POSTGRES_PASSWORD: messagepassword
      POSTGRES_DB: messagedb
    ports:
      - "5432:5432"
    networks:
      message_network:
        ipv4_address: 172.12.0.2

networks:
  message_network:
    name: message_network
    ipam:
      config:
        - subnet: 172.12.0.0/24
